sudo: false
language: node_js
node_js:
  - 10
  - 12
  - 14
cache:
  directories:
    - node_modules
before_script:
  - npm prune
script:
  - npm run lint
  - npm run test-cov
after_script:
  - npm install codecov
  - ./node_modules/.bin/codecov